### ISSUE TITLE
Could not find a version that satisfies the requirement PyQt5 (from rlbot==0.0.*) (from versions: ) No matching distribution found for PyQt5 (from rlbot==0.0.*)

### ISSUE THREAD

**Issue by SamMitchell153** [RLBot/RLBotCSharpExample#3]
Could not find a version that satisfies the requirement PyQt5 (from rlbot==0.0.*) (from versions: )
No matching distribution found for PyQt5 (from rlbot==0.0.*)

Python version unsupported (2.7.15). needs 3.6+

**Comment by tarehart** [comment]
Python 3.6 is required, unfortunately. Please see the installation instructions in the readme.
